services:
  mcpo-control-panel:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
      - "8000:8000"
    volumes:
      - ./data:/data
    environment:
      MCPO_MANAGER_HOST: "0.0.0.0"
      MCPO_MANAGER_PORT: "8083"
      MCPO_MANAGER_DATA_DIR: "/data"
    restart: unless-stopped
    command: ["uv", "run", "python", "-m", "mcpo_control_panel", "--host", "0.0.0.0", "--port", "8083", "--config-dir", "/data"]
